// lib/summarize.ts
// Calls Claude API to generate Slack-ready summaries

import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// ─── Monday Summary ───────────────────────────────────────────────────────────

export async function generateMondaySummary(issuesText: string): Promise<string> {
  const message = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 1024,
    messages: [
      {
        role: "user",
        content: `You are writing a Monday morning standup summary for the #product Slack channel at Enigma Labs, a UAP/UFO sighting platform. The audience is the product and engineering team.

Your summary must follow these rules exactly:

OPENING (use word-for-word, then go straight into the list):
"Morning, team! I hope everyone had a nice weekend. Here's a quick rundown on what Engineering is working on, automatically sourced from Linear."

CLOSING (use word-for-word, in italics using Slack's _italic_ formatting):
"_This summary was generated by AI. If you find inaccurate info, please let me know._"

CATEGORIES — group every issue into exactly one of these five buckets, in this order. Use *bold* Slack formatting for each header with the emoji prefix shown. Skip any category with zero issues.

*📱 Mobile* — iOS and Android app work, including search, filtering, maps, and discovery features when part of the mobile app experience
*🖥 Web* — web app features, pages, or bugs
*⚙ Platform* — backend, API, auth, infrastructure, moderation, trust & safety, admin tooling
*Enterprise* — computer vision, counter-UAS, streaming, Skopos-related work
*Other* — anything that doesn't clearly fit the above

CONSOLIDATION RULES (apply before writing any bullets):
- Before writing bullets, scan all issues and identify clusters that are clearly in service of the same end-user feature or outcome — for example, a backend schema change, an API update, and a moderation logic ticket that all exist to support a single iOS feature should become one bullet
- Write the consolidated bullet from the end-user or product perspective, describing the outcome, not the individual tasks
- A single bullet can represent 2–4 underlying issues if they share an obvious common goal
- Only split into separate bullets when issues are genuinely unrelated

BULLET FORMATTING RULES:
- For issues labeled "bug": write "Fixing a bug that [explain the negative effect in plain English based on the issue title/description]"
- For features or improvements: start with a verb like "Introducing", "Improving", "Enhancing", or "Simplifying", then complete the sentence based on the issue title and description. Example: "Introducing quick filters on Android" or "Improving the initial impression of the homepage"
- Do not include issue IDs, ticket numbers, or assignee names in the final bullets
- Do not editorialize on how close something is to completion (no "nearly there", "close to landing", etc.) — state status factually if needed, but the verb-based phrasing above should usually make this unnecessary

Here are this week's issues (already filtered to only In Progress, In Review, QA, and Ready for Release):

${issuesText}

Write the Slack message now. Do not include any preamble or explanation — just the message itself, starting with the opening line above.`,
      },
    ],
  });

  const content = message.content[0];
  if (content.type !== "text") throw new Error("Unexpected response type from Claude");
  return content.text;
}

// ─── Thursday Digest ──────────────────────────────────────────────────────────

export async function generateThursdayDigest(
  readyForReleaseText: string,
  releasedText: string
): Promise<string> {
  const message = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 1024,
    messages: [
      {
        role: "user",
        content: `You are writing a Thursday end-of-day digest for the #product Slack channel at Enigma Labs, a UAP/UFO sighting platform. The audience is the product and engineering team.

Your digest must follow these rules exactly:

OPENING (use word-for-word, then go straight into the content):
"Happy Thursday, team! Here's a quick look at what crossed the finish line this week, automatically sourced from Linear."

CLOSING (use word-for-word, in italics using Slack's _italic_ formatting):
"_This summary was generated by AI. If you find inaccurate info, please let me know._"

CATEGORIES — group every issue into exactly one of these five buckets, in this order. Use *bold* Slack formatting for each header with the emoji prefix shown. Skip any category with zero issues across both sections.

*📱 Mobile* — iOS and Android app work, including search, filtering, maps, and discovery features when part of the mobile app experience
*🖥 Web* — web app features, pages, or bugs
*⚙ Platform* — backend, API, auth, infrastructure, moderation, trust & safety, admin tooling
*Enterprise* — computer vision, counter-UAS, streaming, Skopos-related work
*Other* — anything that doesn't clearly fit the above

SECTIONS — within each category, use two sub-sections (only include a sub-section if it has issues):
  • *Ready for Release* — issues staged and waiting to ship
  • *Released* — issues already shipped since Monday

If both sections are empty for every category, write only the opening line, then "Nothing crossed the finish line this week." then the closing line.

BULLET FORMATTING RULES:
- All bullets must be written in the past tense — this digest describes work that is done or staged
- For issues labeled "bug": write "Fixed a bug that [explain the negative effect in plain English based on the issue title/description]"
- For features or improvements: start with a past-tense verb like "Introduced", "Improved", "Enhanced", or "Simplified", then complete the sentence based on the issue title and description
- Do not include issue IDs, ticket numbers, or assignee names in the final bullets
- Do not editorialize on how close something is to completion

Issues that moved to Ready for Release since Monday:
${readyForReleaseText}

Issues that moved to Released since Monday:
${releasedText}

Write the Slack message now. Do not include any preamble or explanation — just the message itself, starting with the opening line above.`,
      },
    ],
  });

  const content = message.content[0];
  if (content.type !== "text") throw new Error("Unexpected response type from Claude");
  return content.text;
}
