// lib/summarize.ts
// Calls Claude API to generate Slack-ready summaries

import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// ─── Monday Summary ───────────────────────────────────────────────────────────

export async function generateMondaySummary(issuesText: string): Promise<string> {
  const message = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 1024,
    messages: [
      {
        role: "user",
        content: `You are writing a Monday morning standup summary for the #product Slack channel at Enigma Labs, a UAP/UFO sighting platform. The audience is the product and engineering team.

Your summary must follow these rules exactly:

OPENING (use word-for-word, then go straight into the list):
"Morning, team! I hope everyone had a nice weekend. Here's a quick rundown on what Engineering is working on, automatically sourced from Linear."

CLOSING (use word-for-word):
"This summary was generated by AI. If you find inaccurate info, please let me know."

CATEGORIES — group every issue into exactly one of these five buckets, in this order. Use *bold* Slack formatting for each header. Skip any category with zero issues.

*Mobile* — iOS and Android app work, including search, filtering, maps, and discovery features when part of the mobile app experience
*Web* — web app features, pages, or bugs
*Platform* — backend, API, auth, infrastructure, moderation, trust & safety, admin tooling
*Enterprise* — computer vision, counter-UAS, streaming, Skopos-related work
*Other* — anything that doesn't clearly fit the above

BULLET FORMATTING RULES:
- For issues labeled "bug": write "Fixing a bug that [explain the negative effect in plain English based on the issue title/description]"
- For features or improvements: start with a verb like "Introducing", "Improving", "Enhancing", or "Simplifying", then complete the sentence based on the issue title and description. Example: "Introducing quick filters on Android" or "Improving the initial impression of the homepage"
- Do not include issue IDs, ticket numbers, or assignee names in the final bullets
- Do not editorialize on how close something is to completion (no "nearly there", "close to landing", etc.) — state status factually if needed, but the verb-based phrasing above should usually make this unnecessary

Here are this week's issues (already filtered to only In Progress, In Review, QA, and Ready for Release):

${issuesText}

Write the Slack message now. Do not include any preamble or explanation — just the message itself, starting with the opening line above.`,
      },
    ],
  });

  const content = message.content[0];
  if (content.type !== "text") throw new Error("Unexpected response type from Claude");
  return content.text;
}

// ─── Thursday Digest ──────────────────────────────────────────────────────────

export async function generateThursdayDigest(
  readyForReleaseText: string,
  releasedText: string
): Promise<string> {
  const message = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 1024,
    messages: [
      {
        role: "user",
        content: `You are writing a Thursday end-of-day digest for the #product Slack channel at Enigma Labs, a UAP/UFO sighting platform. The audience is the product and engineering team.

Your digest should:
- Open with a brief "end of week" framing
- Have two clear sections:
  1. *Ready for Release* — issues staged and waiting to ship
  2. *Released This Week* — issues already shipped since Monday
- For each issue, write a brief one-line description in plain English (no issue IDs, no jargon)
- If either section is empty, note it gracefully (e.g. "Nothing new staged for release yet")
- Close with a short forward-looking note about what's coming next week if there are items in Ready for Release
- Use Slack formatting: *bold* for section headers, bullet points with hyphens
- Keep it under 250 words total

Issues that moved to Ready for Release since Monday:
${readyForReleaseText}

Issues that moved to Released since Monday:
${releasedText}

Write the Slack message now. Do not include any preamble or explanation — just the message itself.`,
      },
    ],
  });

  const content = message.content[0];
  if (content.type !== "text") throw new Error("Unexpected response type from Claude");
  return content.text;
}
